### ISSUE TITLE
SDK sync/tidy

### ISSUE THREAD

**Issue by lukeocodes** [deepgram-devs/deepgram-rust-sdk#46]
cc @SandraRodgers 

making a note that we should find some time to look at this SDK in the near future

**Comment by yottalogical** [comment]
I should note that #22 is pretty much finished. The only reason it's not merged is because I didn't finish the documentation before my internship at Deepgram ended.

It has been a while though, so it will be necessary to add any new Deepgram features since August 12, 2022.

**Comment by Manubi** [comment]
@lukeocodes can we please?

**Comment by cenzovit** [comment]
Could someone from deepgram provide any insight on if there has been any movement on this? The SDK for streaming isn't very functional due to the lack of options etc.

**Comment by DamienDeepgram** [comment]
This has been addressed in this PR: https://github.com/deepgram-devs/deepgram-rust-sdk/pull/76
