### ISSUE TITLE
Ungenericify Deepgram struct

### ISSUE THREAD

**Issue by algesten** [deepgram-devs/deepgram-rust-sdk#49]
## Proposed changes

The `Deepgram<K>` struct is generic over the API key `K`. The signature is:

```rust
pub struct Deepgram<K>
where
    K: AsRef<str>,
```

I propose `K` is cloned and stored internally in a `String`.

## Context

There is no obvious benefit to the API user to be generic over an API key. I can see two reasons to do this, and neither seem to hold up.

  1. Save space. However it's 40 bytes as a string (and looks like a hexadecimal number, so I assume it can be stored as a number too?). It seems to be a very small gain.
  2. Allow user to control storage of the API key. In a security paranoid environment maybe it would be possible to hold the key in a "secure enclave" or similar tech. Though `AsRef` would defeat this, since a simple operation is supposed to release the key. If I don't want the `Deepgram` struct to remain in memory with the key, I can simply drop the struct. If the API want to ensure the key is zeroed out from memory, the API can `impl Drop for Deepgram` and zero the memory where the key was stored.

## Possible Implementation

```rust
 fn new(key: impl AsRef<str>) -> Self {
    let api_key = key.as_ref().to_owned();
    Self { api_key }
 }
```

**Comment by lukeocodes** [comment]
hey thanks for this @algesten we'll try and review it asap
