### ISSUE TITLE
Add `smart_format` to the pre-recorded API

### ISSUE THREAD

**Issue by jbolda** [deepgram-devs/deepgram-rust-sdk#64]
## Proposed changes

Add `Options::smart_format` to the SDK.

## Context

The option exists in the API, but is not exposed in the SDK. It looks like this work may have been started in #60, but appears to have stalled.

**Comment by cameronelliott** [comment]
Would be nice.

**Comment by DamienDeepgram** [comment]
This has been addressed in this PR: https://github.com/deepgram-devs/deepgram-rust-sdk/pull/76
